<?php
/**
 * @file
 * A Payment method plugin for the Payment module.
 */

/**
 * Implements hook_permission().
 */
function datatrans_permission() {
  return array(
    'administer datatrans' => array(
      'title' => t('Administer Datatrans configuration'),
      'description' => t('Administer Datatrans module, change settings.'),
    ),
    'anonymous datatrans' => array(
      'title' => t('Datatrans redirect'),
      'description' => t('Use the Datatrans redirect service.'),
    ),
  );
}

/**
 * Implements hook_payment_method_controller_info().
 */
function payment_datatrans_method_controller_info() {
  return array('OgonePaymentMethodController');
}
